# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/git_working/Intelligent-Study-Bot/FPGA/FPGA.srcs/sources_1/ip/Binary_Image_buffer/Binary_Image_buffer.xci
# IP: The module: 'Binary_Image_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_working/Intelligent-Study-Bot/FPGA/FPGA.srcs/sources_1/ip/Binary_Image_buffer/Binary_Image_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Binary_Image_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/git_working/Intelligent-Study-Bot/FPGA/FPGA.srcs/sources_1/ip/Binary_Image_buffer/Binary_Image_buffer.xci
# IP: The module: 'Binary_Image_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_working/Intelligent-Study-Bot/FPGA/FPGA.srcs/sources_1/ip/Binary_Image_buffer/Binary_Image_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Binary_Image_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
